title: ".yttro"
description: ".research .discover .create"

github: [metadata]
markdown: kramdown
theme: jekyll-theme-minimal
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

